# PCA

## PCA example
https://www.d.umn.edu/~mhampton/m4326svd_example.pdf

In [2]:
import numpy as np

In [10]:
# 2 rows, 3 columns
B = np.array([[3,2,2],[2,3,-2]])
print("B\n",B)
print("BT\n",B.T)

B
 [[ 3  2  2]
 [ 2  3 -2]]
BT
 [[ 3  2]
 [ 2  3]
 [ 2 -2]]


In [12]:
# Square matrix: 2x3 dot 3x2 = 2x2
A = B.dot(B.T)
print("A\n",A)

A
 [[17  8]
 [ 8 17]]


## Eigenvalues
Here is how to find the eigenvalues of a 2x2 square matrix.
$Av = \lambda v$   
$Av - \lambda v = 0$   
$( A - \lambda I ) v = 0$  
For any non-trivial solution, $v \neq 0$, so   
$0 = det(A - \lambda I)$  
We want the determinant of matrix  
$ (a-\lambda) (b)$  
$ (c) (d-\lambda)$  
For 2x2 matrix, the determinant = ad-bc so  
$0 = (a-\lambda)(d-\lambda) - b*c$  
$= (17-\lambda)(17-\lambda) - 8*8$  
$= (17^2-2*17*\lambda+\lambda^2) - 64$  
$= (289-34\lambda+\lambda^2) - 64$  
$= \lambda^2 -34\lambda +225$  
  


The characteristic polynomial of A is  
$0 = \lambda^2 -34\lambda +225$  


This quadratic equation   
$ax^2 + bx + c = 0$  
has roots r,s  
$a(x-r)(x-s) = 0$
where  
$r,s=\frac{-b \pm \sqrt{b^2-4ac}}{2a}$  

This quadratic equation   
$\lambda^2 -34\lambda +225 = 0$  
has roots r,s  
$1(\lambda-r)(\lambda-s) = 0$  
where  
$r,s=\frac{34 \pm \sqrt{1156-4*225}}{2}
 =\frac{34 \pm \sqrt{256}}{2}
 =\frac{34 \pm 16}{2}
 =25,9$  
So  
$0 = (\lambda-25)(\lambda-9)$  
The eigenvalues of A are 25 and 9 (and 0?).  
The singular values of A are the square roots, 5 and 3.

In [34]:
eigvals,eigvecs=np.linalg.eig(A)
print("Numpy eigenvalues\n",eigvals)
print("Numpy eigenvectors\n",eigvecs)

Numpy eigenvalues
 [25.  9.]
Numpy eigenvectors
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [35]:
A*eigvecs[0]

array([[ 12.02081528,  -5.65685425],
       [  5.65685425, -12.02081528]])

In [38]:
eigvals[0]*np.identity(2)*eigvecs[0]

array([[ 17.67766953,  -0.        ],
       [  0.        , -17.67766953]])

In [41]:
left=(A-(eigvals[0]*np.identity(2)))*eigvecs[0]
print(left)
print(np.linalg.det(left))

[[-5.65685425 -5.65685425]
 [ 5.65685425  5.65685425]]
0.0


## Eigenvectors
Note A is symmetric so the eigenvectors are orthogonal.

In [26]:
25**2-34*25


-225