Correlation

In [11]:
import numpy as np
from numpy.random import rand, randint, randn, normal
print ("Random int",randint(1,10))
print ("Random uniform",rand(4))
print ("Random standard normal",randn(4))
mean=50
stdev = 10
shape=[3,3]
print ("Random gaussian\n",normal(mean,stdev,shape))

Random int 1
Random uniform [0.08627841 0.19608483 0.66483192 0.49157361]
Random standard normal [-2.34409328  1.58283821  0.32755975 -0.40430305]
Random gaussian
 [[26.40817246 48.05007194 35.99320693]
 [23.9141389  59.43645247 46.14965465]
 [34.54170242 62.63543122 47.62990241]]
