# Singular Value Decomposition
Generalization of eigen decomposition to non-square matrices.

SVD:  
* $A = U \Sigma V^*$  
* U and V are unitary. (For real numbers in A, this means U and V is each orthogonal and $V^*$=$V^T$. For complex A, unitary means the complex conjugate equals the inverse for U and V.)
* A = m x n, U = m x m, $\Sigma$ = m x n, V = n x n.
* $\Sigma$ is diagonal and its non-zero diagonal elements are the singular values.
* Number of singular values = rank(A).
* There is one and only one SVD having singular values in descending order.
* The columns of U and V are orthonormal bases (orthogonal, unit length).

Relationship to eigen decomposition:
* SVD generalizes to non-square matrices (eigen for square only)
* SVD uses $A = U \Sigma V^T$ (eigen uses $A = U \Sigma U^T$
* For $A=B^TB$ or $A=BB^T$, singular values of B are the square roots of the eigen values of A.
* For symmetric matrix A, SVD = eigen (I think).

Facts:
* SVD is used to compute pseudo-inverse of a matrix.
* SVD is used to compute linear least squares (requires pseudo-inverse). 
* SVD is used for Tikhinov regularization (and the special case Ridge regularization).
* rank(A) = number of non-zero singular values.
* Retain only large singular values to achieve low-rank approximation of matrix A.

In [17]:
import numpy as np

## SVD with numpy

Use this example.
Same example was used for Eigen.  
https://www.d.umn.edu/~mhampton/m4326svd_example.pdf

### Square symmetric matrix

In [18]:
# 2 rows, 3 columns
B = np.array([[3,2,2],[2,3,-2]])
A = B.dot(B.T)
print("Square matrix A = BBT\n",A)

Square matrix A = BBT
 [[17  8]
 [ 8 17]]


In [19]:
U,Sigma,Vt = np.linalg.svd(A)
print("U\n",U);
print("Sigma\n",Sigma);
print("V transpose\n",Vt);

U
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Sigma
 [25.  9.]
V transpose
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


### Non-square matrix

In [20]:
U,Sigma,Vt = np.linalg.svd(B)
print("U\n",U);
print("Singular values in descending order\n",Sigma);
print("V transpose\n",Vt);

U
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Sigma
 [5. 3.]
V transpose
 [[-7.07106781e-01 -7.07106781e-01 -6.47932334e-17]
 [-2.35702260e-01  2.35702260e-01 -9.42809042e-01]
 [-6.66666667e-01  6.66666667e-01  3.33333333e-01]]


Round-trip validation. Use B=U*S*V.

In [35]:
S = [[5,0,0],[0,3,0]]  
print("Round trip validation:\n",U.dot(S).dot(Vt))

Round trip validation:
 [[ 3.  2.  2.]
 [ 2.  3. -2.]]
