# CNN 305
Start with CNN 304 which uses Conv1D layers.

No need for K-mers with convolution. End reliance on make_kmers().

In [1]:
NC_FILENAME='ncRNA.tiny50.fasta'
PC_FILENAME='pcRNA.tiny50.fasta'
#NC_FILENAME='ncRNA.gc34.processed.fasta'
#PC_FILENAME='pcRNA.gc34.processed.fasta'

MODEL_FILE='CNN305'  
DATAPATH=''

try:
    from google.colab import drive
    IN_COLAB = True
    PATH='/content/drive/'
    drive.mount(PATH)
    DATAPATH=PATH+'My Drive/data/'  # must end in "/"
except:
    IN_COLAB = False
    DATAPATH='data/'  # must end in "/"
NC_FILENAME = DATAPATH+NC_FILENAME
PC_FILENAME = DATAPATH+PC_FILENAME
MODEL_FILE=DATAPATH+MODEL_FILE

EPOCHS=5
SPLITS=1
K=1
VOCABULARY_SIZE=4**K+1   # e.g. K=3 => 64 DNA K-mers + 'NNN'
EMBED_DIMEN=2
FILTERS=16
KERNEL=3
NEURONS=16
DROP=0.25
ACT="tanh"

In [2]:
# Load our own tools
# TO DO: don't go to GitHub if the file is already local.
GITHUB = True
if GITHUB:
    #!pip install requests  # Uncomment this if necessary. Seems to be pre-installed.
    import requests
    r = requests.get('https://raw.githubusercontent.com/ShepherdCode/ShepherdML/master/Strings/tools_fasta.py')
    with open('tools_fasta.py', 'w') as f:
        f.write(r.text)
    # TO DO: delete the file after import
import tools_fasta as tools
tools.yahoo()  # If this prints "Yahoo!" the the import was successful.

TOOLS_CHANGED = False   # set to True to re-run with a new version of tools
if TOOLS_CHANGED:
  from importlib import reload 
  tools=reload(tools)
  print(dir(tools))   # run this to see EVERYTHING in the tools module

Yahoo!


In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import StratifiedKFold
import tensorflow as tf
from tensorflow import keras
import time
dt='float32'
tf.keras.backend.set_floatx(dt)

Build model

In [4]:
def compile_model(model):
    ## learn rate = initial_learning_rate * decay_rate ^ (step / decay_steps)
    #adam_default_learn_rate = 0.001
    #schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    #    initial_learning_rate = adam_default_learn_rate*10,
    #    decay_steps=10000, decay_rate=0.99, staircase=True)
    #alrd = tf.keras.optimizers.Adam(learning_rate=schedule)
    #model.compile(loss=bc, optimizer=alrd, metrics=["accuracy"])

    print("COMPILE...")
    bc=tf.keras.losses.BinaryCrossentropy(from_logits=False)
    model.compile(loss=bc, optimizer="adam", metrics=["accuracy"])
    print("...COMPILED")
    return model

def build_model():
    SHAPE=(1000,5)  # 1000 time steps, 5 features
    clayer1 = keras.layers.Conv1D(FILTERS,KERNEL,activation=ACT,padding="same",
                                 input_shape=SHAPE)
    clayer2 = keras.layers.Conv1D(FILTERS,KERNEL,activation=ACT,padding="same")
    clayer3 = keras.layers.MaxPooling1D(2)
    clayer4 = keras.layers.Conv1D(FILTERS,KERNEL,activation=ACT,padding="same")
    clayer5 = keras.layers.Conv1D(FILTERS,KERNEL,activation=ACT,padding="same")
    clayer6 = keras.layers.MaxPooling1D(2)
    clayer7 = keras.layers.Flatten()

    dlayer1 = keras.layers.Dense(NEURONS, activation=ACT,dtype=dt, input_shape=[1000])
    dlayer2 = keras.layers.Dropout(DROP)
    dlayer3 = keras.layers.Dense(NEURONS, activation=ACT,dtype=dt)
    dlayer4 = keras.layers.Dropout(DROP)
    output_layer = keras.layers.Dense(1, activation="sigmoid", dtype=dt)

    cnn = keras.models.Sequential()
    cnn.add(clayer1)
    cnn.add(clayer2)
    cnn.add(clayer3)
    cnn.add(clayer4)
    cnn.add(clayer5)
    cnn.add(clayer6)
    cnn.add(clayer7)
    cnn.add(dlayer1)
    cnn.add(dlayer2)
    cnn.add(dlayer3)
    cnn.add(dlayer4)
    cnn.add(output_layer)
    mlpc = compile_model(cnn)
    return mlpc

Cross validation

In [18]:
def do_cross_validation(X,y,given_model):
    cv_scores = []
    fold=0
    splitter = ShuffleSplit(n_splits=SPLITS, test_size=0.1, random_state=37863)
    for train_index,valid_index in splitter.split(X):
        fold += 1
        print(train_index)
        print(type(train_index))
        print(type(train_index[0]))

        X_train=X[train_index] # use iloc[] for dataframe
        y_train=y[train_index]
        X_valid=X[valid_index]
        y_valid=y[valid_index]        
        # Avoid continually improving the same model.
        model = compile_model(keras.models.clone_model(given_model))
        bestname=MODEL_FILE+".cv."+str(fold)+".best"
        mycallbacks = [keras.callbacks.ModelCheckpoint(
            filepath=bestname, save_best_only=True, 
            monitor='val_accuracy', mode='max')]   
        print("FIT")
        start_time=time.time()
        history=model.fit(X_train, y_train, # batch_size=10, default=32 works nicely
                epochs=EPOCHS, verbose=1,  # verbose=1 for ascii art, verbose=0 for none
                callbacks=mycallbacks,
                validation_data=(X_valid,y_valid) )
        end_time=time.time()
        elapsed_time=(end_time-start_time)                        
        print("Fold %d, %d epochs, %d sec"%(fold,EPOCHS,elapsed_time))
        pd.DataFrame(history.history).plot(figsize=(8,5))
        plt.grid(True)
        plt.gca().set_ylim(0,1)
        plt.show()
        best_model=keras.models.load_model(bestname)
        scores = best_model.evaluate(X_valid, y_valid, verbose=0)
        print("%s: %.2f%%" % (best_model.metrics_names[1], scores[1]*100))
        cv_scores.append(scores[1] * 100)  
    print()
    print("%d-way Cross Validation mean %.2f%% (+/- %.2f%%)" % (fold, np.mean(cv_scores), np.std(cv_scores)))

## Train on RNA lengths 200-1Kb

## to do:
Stop calling make_kmers() then onehot().
We're only using make_kmers convert ACGT to 1234.
Instead, write an RNA_to_onehot() function.

In [19]:
print ("Compile the model")
model=build_model()
print ("Summarize the model")
print(model.summary())  # Print this only once
#model.save(MODEL_FILE+'.model')


Compile the model
COMPILE...
...COMPILED
Summarize the model
Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_8 (Conv1D)            (None, 1000, 16)          256       
_________________________________________________________________
conv1d_9 (Conv1D)            (None, 1000, 16)          784       
_________________________________________________________________
max_pooling1d_4 (MaxPooling1 (None, 500, 16)           0         
_________________________________________________________________
conv1d_10 (Conv1D)           (None, 500, 16)           784       
_________________________________________________________________
conv1d_11 (Conv1D)           (None, 500, 16)           784       
_________________________________________________________________
max_pooling1d_5 (MaxPooling1 (None, 250, 16)           0         
___________________________________________________________

In [22]:
MINLEN=200
MAXLEN=1000
print("Load data from files.")
nc_seq=tools.load_fasta(NC_FILENAME,0)
pc_seq=tools.load_fasta(PC_FILENAME,1)
train_set=pd.concat((nc_seq,pc_seq),axis=0)
nc_seq=None
pc_seq=None
print("Ready: train_set")
#train_set
subset=tools.make_slice(train_set,MINLEN,MAXLEN)# One array to two: X and y
(X1,y_train)=tools.separate_X_and_y(subset)
# X1 is pandas df of ("list" of one sequence)
X2=X1.to_numpy()  # numpy ndarray of ("list" of one sequence)
X3=[elem[0] for elem in X2]  # numpy dnarray of str

def uniform_length(lst,UNI_LEN):
    # For speed, assume no element longer than UNI_LEN.
    # This function breaks if assumption is violated.
    #return np.array([i for i in lst])
    return np.array([i + 'N'*(UNI_LEN-len(i)) for i in lst])

X4=uniform_length(X3,MAXLEN)
X5= [tools.one_hot(x) for x in X4]

###(X_train,y_train)=tools.make_kmers(K,MAXLEN,subset)
###X_train=tools.onehot(X_train)

#X_train=pd.DataFrame()
#X_train['sequence']=X5
X_train=np.asarray(X5)
#print("First sequence as onehot")
#print(X_train[0])
print(type(X_train))
print(X_train[[2,4]])

subset=None
X1=None
X2=None
X3=None
X4=None
X5=None

Load data from files.
Ready: train_set
<class 'numpy.ndarray'>
[[[0 0 0 1 0]
  [0 0 0 1 0]
  [0 0 1 0 0]
  ...
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]]

 [[1 0 0 0 0]
  [0 0 0 1 0]
  [0 0 0 1 0]
  ...
  [0 0 0 0 1]
  [0 0 0 0 1]
  [0 0 0 0 1]]]


In [24]:
print ("Cross valiation")
print(type(X_train))
print(X_train.shape)
print(type(y_train))
print(y_train.shape)
do_cross_validation(X_train,y_train,model)  
print ("Done")

Cross valiation
<class 'numpy.ndarray'>
(100, 1000, 5)
<class 'pandas.core.frame.DataFrame'>
(100, 1)
[49 18 68 55 43 75 28 56 53  1 95 60 47 93 51 78 13 32 14 72 90 52 50 21
  9 70 81 34 27 99 25 73 37 29 58 26 82 80  6 87 67 22  5 92 91 83 94 33
  7 65 79 62 16 76 19 15 63 57 12 36 84  2 98  0  3 41 38 54 45 10 69 77
 17 71 20 59 39 44 11 89 35 46 85 42 74 23 96 24 64 88]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


KeyError: "None of [Int64Index([49, 18, 68, 55, 43, 75, 28, 56, 53,  1, 95, 60, 47, 93, 51, 78, 13,\n            32, 14, 72, 90, 52, 50, 21,  9, 70, 81, 34, 27, 99, 25, 73, 37, 29,\n            58, 26, 82, 80,  6, 87, 67, 22,  5, 92, 91, 83, 94, 33,  7, 65, 79,\n            62, 16, 76, 19, 15, 63, 57, 12, 36, 84,  2, 98,  0,  3, 41, 38, 54,\n            45, 10, 69, 77, 17, 71, 20, 59, 39, 44, 11, 89, 35, 46, 85, 42, 74,\n            23, 96, 24, 64, 88],\n           dtype='int64')] are in the [columns]"