# n-grams
We commonly extract K-mers from RNA sequence. 
K-mers are called n-grams in TensorFlow.
They are substrings of length K or length n.
We have home-grown code to extract K-mers in Strings/tools_fasta.py.
Here, explore the TensorFlow ngrams class.

## Documentation

Avoid the old documentation for 
(ngrams)[https://www.tensorflow.org/tfx/transform/api_docs/python/tft/ngrams]. 
The only way to know it is TensorFlow 1 is that it doesn't many any version. 

Here is the documentation for 
(ngrams)[https://www.tensorflow.org/api_docs/python/tf/strings/ngrams] 
in TensorFlow 2.
The documentation is very hard to understand. The examples are not helpful.

This simple text intro 
(blog)[https://dzlab.github.io/nlp/2019/12/25/tensorflow-text-intro/] 
demonstrates how to use TensorFlow ngrams.

This 
(tutorial)[https://blog.codecentric.de/en/2019/07/move-n-gram-extraction-into-your-keras-model/] 
shows how to implement ngrams as convolutions with numpy 
or Keras lambda function
or Keras 1D convolution.

Somebody built a Keras Layer called 
(NGram)[https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/layers/ngram.py].
Not clear why. 



In [19]:
import tensorflow as tf
from tensorflow.strings import ngrams
data=[]
data.append('ABCDEFG')
data.append('HIJKLMN')
data.append('OPQRSTU')
data.append('VWXYZAB')
print("data=\n",data)


data=
 ['ABCDEFG', 'HIJKLMN', 'OPQRSTU', 'VWXYZAB']


In [20]:
ng=ngrams(data,2)
print("2grams=\n",ng)
# This generates all consecutive pairs of words separated by space (default).

2grams=
 tf.Tensor([b'ABCDEFG HIJKLMN' b'HIJKLMN OPQRSTU' b'OPQRSTU VWXYZAB'], shape=(3,), dtype=string)


In [22]:
# Convert strings to character arrays.
letters=list(map(list,data))
letters

[['A', 'B', 'C', 'D', 'E', 'F', 'G'],
 ['H', 'I', 'J', 'K', 'L', 'M', 'N'],
 ['O', 'P', 'Q', 'R', 'S', 'T', 'U'],
 ['V', 'W', 'X', 'Y', 'Z', 'A', 'B']]

In [26]:
ng=ngrams(letters,3)
print("2grams=\n",ng)
# This generates 3-mers with spaces (by default)

2grams=
 tf.Tensor(
[[b'A B C' b'B C D' b'C D E' b'D E F' b'E F G']
 [b'H I J' b'I J K' b'J K L' b'K L M' b'L M N']
 [b'O P Q' b'P Q R' b'Q R S' b'R S T' b'S T U']
 [b'V W X' b'W X Y' b'X Y Z' b'Y Z A' b'Z A B']], shape=(4, 5), dtype=string)


In [28]:
ng=ngrams(letters,3,separator='')
print("2grams=\n",ng)
# This generates 3-mers the way we like 

2grams=
 tf.Tensor(
[[b'ABC' b'BCD' b'CDE' b'DEF' b'EFG']
 [b'HIJ' b'IJK' b'JKL' b'KLM' b'LMN']
 [b'OPQ' b'PQR' b'QRS' b'RST' b'STU']
 [b'VWX' b'WXY' b'XYZ' b'YZA' b'ZAB']], shape=(4, 5), dtype=string)
