# Statistics

In [1]:
import datetime
print(datetime.datetime.now())
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import StratifiedKFold
import csv
import os

2022-08-02 14:54:42.355225


In [2]:
LABFILE='/home/jrm/Adjeroh/Glioma/August_Run/TrainValidSplits/aug_case_labels.csv'
SPLITFILE='/home/jrm/Adjeroh/Glioma/August_Run/TrainValidSplits/aug_train_valid_splits.csv'
DATA_DIR='/home/jrm/Adjeroh/Glioma/August_Run/CellProfilerPerPatient/'
FILENAME='Process100_Image.csv'

In [3]:
cases = pd.read_csv(LABFILE,names=['Case','Class'])
cases

Case  Class
0    TCGA-02-0004-01Z-00      0
1    TCGA-02-0010-01Z-00      0
2    TCGA-14-0789-01Z-00      0
3    TCGA-02-0025-01Z-00      0
4    TCGA-02-0033-01Z-00      0
..                   ...    ...
122  TCGA-S9-A6U1-01Z-00      4
123  TCGA-DB-A4XG-01Z-00      5
124  TCGA-HT-A5R9-01Z-00      5
125  TCGA-QH-A6CU-01Z-00      5
126  TCGA-DH-A66G-01Z-00      5

[127 rows x 2 columns]

In [5]:
case_to_class = {}
cases_per_class = np.zeros(6,dtype=int)
for ndx,row in cases.iterrows():
    case = row['Case']
    cls = row['Class']
    case_to_class[case] = cls 
    cases_per_class[cls] = cases_per_class[cls]+1 
print(cases_per_class)

[46 21 17 15 15 13]


In [8]:
patches_per_class = np.zeros(6,dtype=int)
total_patches = 0
for case,cls in case_to_class.items():
    print('.',end='')
    directory = case + '/'
    fullpath = DATA_DIR + directory + FILENAME
    df = pd.read_csv(fullpath)
    num_patches = len(df)
    cls = case_to_class[case]
    patches_per_class[cls] = patches_per_class[cls] + num_patches
    total_patches += num_patches
print('\nTotal patches:',total_patches)
print(patches_per_class)
# [44966 12902 13950  6727  6410  5993]

...............................................................................................................................
Total patches: 90948
[44966 12902 13950  6727  6410  5993]


In [9]:
print('Best strategy = always guess major class 0.')
print('Accuracy = majority_size/total = ',patches_per_class[0],'/',total_patches,'=',
     100. * patches_per_class[0] / total_patches)

Best strategy = always guess major class 0.
Accuracy = majority_size/total =  44966 / 90948 = 49.441439064080576


In [11]:
print('Frequentist strategy = guess each class in proportion to its size.')
print('Accuracy = [sum (prob class * prob being right)/ total patches] = ')
numerator = 0
for cls in range(6):
    prob_class = patches_per_class[cls] / total_patches
    term = prob_class**2
    print('+',term,end='')
    numerator += term
print('/',total_patches,'=',numerator/total_patches)


Frequentist strategy = guess each class in proportion to its size.
Accuracy = [sum (prob class * prob being right)/ total patches] = 
+ 0.24444558967271923+ 0.02012462371958696+ 0.023526759284326744+ 0.005470871940442775+ 0.004967407089581819+ 0.004342124275212724/ 90948 = 3.330225799158533e-06
