# Eigen Decomposition
Matrix A must be diagnalizable i.e. square and invertible.  
Same as spectral decomposition of A is symmetric (and contains real numbers not complex numbers).  
The eigenvalues are unique but the eigenvectors are not;
multiples of eigenvectors work just as well since the formula multiplies them by their inverse.  
The eigenvectors can be normalized to length=1.  
The eigenvalues (with their corresponding eigenvectors) can be rearranged from largest to smallest.  
The eigenvectors from the smallest eigenvalues can be discarded for an approximation.  

The decomposition of A can be written  
$A = Q \Lambda Q^{-1}$  
where Q is a matrix of eigen column vectors,  
$Q^{-1}$ is the inverse,   
and big Lambda $\Lambda$ is a diagonal matrix of the little-lambda $\lambda$ eigenvalues in order.  

## Example 
From [wikipedia](https://en.wikipedia.org/wiki/Eigendecomposition_of_a_matrix)

In [1]:
A = [[1,0],[1,3]]
print(A)

[[1, 0], [1, 3]]


In [2]:
import numpy as np
eigenvalues,eigenvectors=np.linalg.eig(A)
print('eigenvalues\n',eigenvalues)
print('eigenvectors\n',eigenvectors)

eigenvalues
 [3. 1.]
eigenvectors
 [[ 0.          0.89442719]
 [ 1.         -0.4472136 ]]


In [3]:
diagonal = eigenvalues * np.identity(2)
print('diagonal\n',diagonal)
R = eigenvectors.dot(diagonal.dot(np.linalg.inv(eigenvectors)))
print('reconstruction\n',R)

diagonal
 [[3. 0.]
 [0. 1.]]
reconstruction
 [[1. 0.]
 [1. 3.]]


## Another example
From [UTDallas](https://personal.utdallas.edu/~herve/Abdi-EVD2007-pretty.pdf)

Eigenvalue 4 has eigenvector column( 3 2 ).
Eigenvalue -1 has eigenvector column ( -1 1 ).


In [4]:
A = [[2,3],[2,1]]
eigenvalues,eigenvectors=np.linalg.eig(A)
print('eigenvalues\n',eigenvalues)
print('eigenvectors\n',eigenvectors)

eigenvalues
 [ 4. -1.]
eigenvectors
 [[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


Numpy's eigenvectors are proportional to the given ones.

In [5]:
E = np.multiply ( eigenvectors, [[3.7,1.5],[3.7,1.5]])   # Hadamard product
print(E)

[[ 3.07858609 -1.06066017]
 [ 2.05239073  1.06066017]]


In fact, numpy's eigenvectors are normalized to length 1, as shown here.

In [6]:
evec0 = E[:,0]
evec1 = E[:,1]
len0 = np.sqrt(evec0.dot(evec0))
len1 = np.sqrt(evec1.dot(evec1))
evec0 = evec0 / len0   # divide by vector length so length = 1
evec1 = evec1 / len1
normvectors = np.column_stack( (evec0,evec1) )
print('eigenvalues\n',eigenvalues)
print('normalized eigenvectors\n',normvectors)

eigenvalues
 [ 4. -1.]
normalized eigenvectors
 [[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


Reconstruct the original.

In [7]:
diagonal = eigenvalues * np.identity(2)
print('diagonal\n',diagonal)
R = eigenvectors.dot(diagonal.dot(np.linalg.inv(eigenvectors)))
print('reconstruction\n',R)

diagonal
 [[ 4. -0.]
 [ 0. -1.]]
reconstruction
 [[2. 3.]
 [2. 1.]]


Success!