# Numpy vectors
By default, numpy vectors are neither column vectors nor row vectors.
They are truly 1D, just vectors.
Numpy does the transpose if necessary.
This can be confusing!

There are various ways to convince numpy to use a row or column vector.

In [1]:
import numpy as np
# Utility function
def show(mat):
    print(mat)
    print(mat.ndim,'dimensions.',mat.shape,'shape.')
# Test the utility
mat = np.zeros( (3,4) )
show(mat)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2 dimensions. (3, 4) shape.


## Vectors have no orientation by default

In [8]:
print('Vector with no orientation')
vector=np.array([1,2,3])
show(vector)
print('Numpy does automatic transpose for dot product to produce a scalar')
show(vector.dot(vector)) 

Vector with no orientation
[1 2 3]
1 dimensions. (3,) shape.
Numpy does automatic transpose for dot product to produce a scalar
14
0 dimensions. () shape.


## Explicit row or column vectors

In [3]:
print('Row vector: one row, three columns')
R=np.array([[1,2,3]])  # one way to make a row vector
show(R)
print('Transpose: three rows, one column')  # one way to make a column vector
C = R.transpose()   
show(C)
# Now, numpy insists that R is row vector and C is column vector.
# Numpy raises exception unless the dot product is given one of each.
print('row dot col = 1x3 dot 3x1 = 1x1 matrix')
show(R.dot(C))

Row vector: one row, three columns
[[1 2 3]]
2 dimensions. (1, 3) shape.
Transpose: three rows, one column
[[1]
 [2]
 [3]]
2 dimensions. (3, 1) shape.
row dot col = 1x3 dot 3x1 = 1x1 matrix
[[14]]
2 dimensions. (1, 1) shape.


In [4]:
print('Row vector: one row, three columns')
R=np.array([1,2,3])
R.shape=(1,3)  # another way to make a row vector
show(R)
print('Transpose: three rows, one column') # make a column vector
T = R.transpose()   
show(T)
print('row dot col = 1x3 dot 3x1 = 1x1 matrix')
show(R.dot(T))

Row vector: one row, three columns
[[1 2 3]]
2 dimensions. (1, 3) shape.
Transpose: three rows, one column
[[1]
 [2]
 [3]]
2 dimensions. (3, 1) shape.
row dot col = 1x3 dot 3x1 = 1x1 matrix
[[14]]
2 dimensions. (1, 1) shape.


In [5]:
print('Column vector: one column, three rows')
C=np.array([[1,2,3]]).T  # one way to make a column vector
show(C)
print('Transpose: three columns, one row')
T = C.transpose()   # row vector
show(T)
print('col dot row = 3x1 dot 1x3 = 3x3 matrix')
show(C.dot(T))
print('row dot col = 1x3 dot 3x1 = 1x1 matrix = scalar')
show(T.dot(C))

Column vector: one column, three rows
[[1]
 [2]
 [3]]
2 dimensions. (3, 1) shape.
Transpose: three columns, one row
[[1 2 3]]
2 dimensions. (1, 3) shape.
col dot row = 3x1 dot 1x3 = 3x3 matrix
[[1 2 3]
 [2 4 6]
 [3 6 9]]
2 dimensions. (3, 3) shape.
row dot col = 1x3 dot 3x1 = 1x1 matrix = scalar
[[14]]
2 dimensions. (1, 1) shape.


In [6]:
print('Column vector: one column, three rows')
C=np.array([1,2,3])  
C.shape=(3,1)  # another way to make a column vector: 3 rows, 1 column
show(C)
print('Transpose: three rows, one column')
T = C.transpose()   
show(T)
print('C.dot(transpose)')
show(C.dot(T)) 

Column vector: one column, three rows
[[1]
 [2]
 [3]]
2 dimensions. (3, 1) shape.
Transpose: three rows, one column
[[1 2 3]]
2 dimensions. (1, 3) shape.
C.dot(transpose)
[[1 2 3]
 [2 4 6]
 [3 6 9]]
2 dimensions. (3, 3) shape.
