# Numpy vectors

In [1]:
import numpy as np
def show(mat):
    print(mat)
    print(mat.ndim,'dimensions.',mat.shape,'shape.')

In [2]:
mat = np.zeros( (3,4) )
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
print('Vector with no orientation')
vector=np.array([1,2,3])
show(vector)
print('Numpy does automatic transpose for dot product')
print(vector.dot(vector)) 

Vector with no orientation
[1 2 3]
1 dimensions. (3,) shape.
Numpy does automatic transpose for dot product
14


In [4]:
print('Row vector: one row, three columns')
vector=np.array([[1,2,3]])  # one way to make a row vector
show(vector)
print('Transpose: three rows, one column')
T = vector.transpose()   
show(T)
# Numpy raises exception unless dot product given transpose
print('row dot col = 1x3 dot 3x1 = 1x1 matrix\n',vector.dot(T))

Row vector: one row, three columns
[[1 2 3]]
2 dimensions. (1, 3) shape.
Transpose: three rows, one column
[[1]
 [2]
 [3]]
2 dimensions. (3, 1) shape.
row dot col = 1x3 dot 3x1 = 1x1 matrix
 [[14]]


In [5]:
print('Row vector: one row, three columns')
vector=np.array([1,2,3])
vector.shape=(1,3)  # another way to make a row vector
show(vector)
print('Transpose: three rows, one column')
T = vector.transpose()   
show(T)
print('row dot col = 1x3 dot 3x1 = 1x1 matrix\n',vector.dot(T))

Row vector: one row, three columns
[[1 2 3]]
2 dimensions. (1, 3) shape.
Transpose: three rows, one column
[[1]
 [2]
 [3]]
2 dimensions. (3, 1) shape.
row dot col = 1x3 dot 3x1 = 1x1 matrix
 [[14]]


In [6]:
print('Column vector: one column, three rows')
vector=np.array([[1,2,3]]).T  # one way to make a column vector
show(vector)
print('Transpose: three columns, one row')
T = vector.transpose()   
show(T)
print('col dot row = 3x1 dot 1x3 = 3x3 matrix')
print(vector.dot(T))

Column vector: one column, three rows
[[1]
 [2]
 [3]]
2 dimensions. (3, 1) shape.
Transpose: three columns, one row
[[1 2 3]]
2 dimensions. (1, 3) shape.
col dot row = 3x1 dot 1x3 = 3x3 matrix
[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [7]:
print('Column vector: one column, three rows')
vector=np.array([1,2,3])  
vector.shape=(3,1)  # another way to make a column vector: 3 rows, 1 column
show(vector)
print('Transpose: three rows, one column')
T = vector.transpose()   
show(T)
print(vector.dot(T)) 

Column vector: one column, three rows
[[1]
 [2]
 [3]]
2 dimensions. (3, 1) shape.
Transpose: three rows, one column
[[1 2 3]]
2 dimensions. (1, 3) shape.
[[1 2 3]
 [2 4 6]
 [3 6 9]]
