# Pretrained D&E classifier


In [1]:
import time
import os
#  os.environ['CUDA_VISIBLE_DEVICES'] = "0"   # turns off GPU?
import glob
#import cv2 # OpenCV-Python
#from PIL import Image
#Image.MAX_IMAGE_PIXELS = None
import numpy as np
import json
from tensorflow import keras
import keras.layers as kl
import pandas as pd
import matplotlib.pyplot as plt

from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input

print('\n'.join(f'{m.__name__}=={m.__version__}' for m in globals().values() if getattr(m, '__version__', None)))

numpy==1.22.1
json==2.0.9
keras.api._v2.keras==2.7.0
pandas==1.4.0


In [2]:
DIR_IMAGES_IN = "/home/jrm/Martinez/images/Crop/"  
PATCH_SIZE=224  # matches VGG
DIR_MODELS = "/home/jrm/Martinez/models/"
FILE_MODEL = "DF_Filter.032"  # load the old model
filepath=DIR_MODELS+FILE_MODEL
print("Will reuse model at "+filepath)
BATCH_SIZE = 32
IMG_SIZE = (PATCH_SIZE,PATCH_SIZE)
CHANNELS = 3

Will reuse model at /home/jrm/Martinez/models/DF_Filter.032


In [5]:
test_dir = os.path.join(DIR_IMAGES_IN, 'test/')
test_dataset = keras.utils.image_dataset_from_directory(
    test_dir, shuffle=False, batch_size=BATCH_SIZE, image_size=IMG_SIZE)


Found 114 files belonging to 2 classes.


In [6]:
# Normalize color channel ints to floats (0,1)
# See https://www.tensorflow.org/tutorials/load_data/images

normalization_layer = kl.Rescaling(1.0/255.0)
test_dataset = test_dataset.map(lambda x, y: (normalization_layer(x), y))


In [8]:
iterator = test_dataset.take(10)
for x in iterator:
    print(x[0].shape)
    print(x[1])

(32, 224, 224, 3)
tf.Tensor([0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0], shape=(32,), dtype=int32)
(32, 224, 224, 3)
tf.Tensor([0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1], shape=(32,), dtype=int32)
(32, 224, 224, 3)
tf.Tensor([1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1], shape=(32,), dtype=int32)
(18, 224, 224, 3)
tf.Tensor([1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1], shape=(18,), dtype=int32)


In [11]:
model = keras.models.load_model(filepath)
start = time.time()
hist = model.predict(test_dataset)
end = time.time()
print("Elapsed time:",end-start)

Elapsed time: 3.7473862171173096


In [13]:
len(hist)

114

In [12]:
hist

array([[0.913375  , 0.08662494],
       [0.956854  , 0.04314594],
       [0.9181756 , 0.08182438],
       [0.92338324, 0.07661674],
       [0.9569172 , 0.04308278],
       [0.9769359 , 0.02306407],
       [0.93002975, 0.06997027],
       [0.9630819 , 0.03691813],
       [0.9600411 , 0.03995889],
       [0.87550193, 0.12449808],
       [0.9543028 , 0.04569717],
       [0.9575114 , 0.04248863],
       [0.9504416 , 0.04955845],
       [0.93712145, 0.0628785 ],
       [0.5765299 , 0.42347005],
       [0.92178714, 0.07821278],
       [0.94896996, 0.05103   ],
       [0.8572042 , 0.14279585],
       [0.8620676 , 0.1379324 ],
       [0.9541091 , 0.04589095],
       [0.95545477, 0.04454524],
       [0.64876246, 0.3512375 ],
       [0.9454828 , 0.05451715],
       [0.89506304, 0.10493696],
       [0.9638355 , 0.03616458],
       [0.94273365, 0.05726637],
       [0.7994587 , 0.20054132],
       [0.9588838 , 0.04111622],
       [0.9657557 , 0.03424437],
       [0.9283492 , 0.0716508 ],
       [0.