In [2]:
import numpy as np
import scipy.stats as ss
import pandas
import keras
import sklearn
import tensorflow
import matplotlib
print("numpy", np.__version__)
print("pandas", pandas.__version__)
print("keras", keras.__version__)
print("sklearn", sklearn.__version__)
print("tensorflow", tensorflow.__version__)
print("matplotlib", matplotlib.__version__)


numpy 1.18.4
pandas 1.0.5
keras 2.4.3
sklearn 0.23.1
tensorflow 2.2.0
matplotlib 3.2.2


In [2]:
X=np.ones(10)
W=np.ones(10)
W

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
dot_product = X.dot(W)
dot_product

10.0

In [13]:
W=np.ones([5,10])
print(np.shape(W),np.shape(X))

(5, 10) (10,)


In [14]:
dot_product = W.dot(X)
print(np.shape(dot_product))
dot_product

(5,)


array([10., 10., 10., 10., 10.])

# Python Dictionary

In [4]:
mylist = []
mydict = {}
mydict [ 'CPU' ] = "Central Processing Unit"
mydict [ 'ALU' ] = "Arithmetic and Logic Unit"
mydict [ 'FPU' ] = "Floating Point Unit"

In [5]:
mydict

{'CPU': 'Central Processing Unit',
 'ALU': 'Arithmetic and Logic Unit',
 'FPU': 'Floating Point Unit'}

In [6]:
print (mydict['ALU'])

Arithmetic and Logic Unit


In [7]:
if 'BUS' in mydict:
    print("Got it!")
else:
    print("Not found!")

Not found!


In [8]:
for word in mydict:
    print("The definition of ", word, " is ", mydict[word])

The definition of  CPU  is  Central Processing Unit
The definition of  ALU  is  Arithmetic and Logic Unit
The definition of  FPU  is  Floating Point Unit


In [5]:
import numpy as np
A=(93.85, 92.36, 90.63, 94.54, 93.48)
M=np.mean(A)
S=np.std(A)
M,S

(92.97200000000001, 1.367265884895841)

In [2]:
mlp203=(75.23,75.05,74.92,74.67,75.42)
mlp205=(85.97,85.85,85.54,85.29,86.65)
ss.mannwhitneyu(mlp203,mlp205)
# requires at least 20 observations per sample

MannwhitneyuResult(statistic=0.0, pvalue=0.006092890177672406)

In [3]:
ss.ttest_ind(mlp203,mlp205)
# assumes both normal and variances are equal

Ttest_indResult(statistic=-40.9172537526874, pvalue=1.4012413845559694e-10)

In [4]:
ss.ttest_ind(mlp203,mlp205,equal_var=False)
# assumes both normal

Ttest_indResult(statistic=-40.9172537526874, pvalue=7.563720623586533e-09)

In [6]:
gru219=(93.98,89.45,92.24,89.57,93.05)
gru220=(93.61,85.04,94.04,92.36,91.19)
ss.ttest_ind(gru219,gru220,equal_var=False)

Ttest_indResult(statistic=0.21906573368207619, pvalue=0.8335135668608495)

In [7]:
ss.mannwhitneyu(gru219,gru220)

MannwhitneyuResult(statistic=11.0, pvalue=0.41726581135546437)

In [7]:
gru215=(93.85,92.36, 90.63, 94.54, 93.48, 92.86, 87.40, 88.21, 92.36, 86.96)
gru217=(87.77, 90.94, 88.27, 87.40, 84.79)
M=np.mean(gru215)
S=np.std(gru215)
print(M,S)
print(np.sort(gru215))
ss.ttest_ind(gru217,gru215,equal_var=False)

91.26500000000001 2.6544990111130216
[86.96 87.4  88.21 90.63 92.36 92.36 92.86 93.48 93.85 94.54]


Ttest_indResult(statistic=-2.5952867889778277, pvalue=0.026402569994122466)

In [8]:
#gru
params=(49169,49361,50129,53201,65489)
accuracy=(87.83,87.44,91.27,87.61,86.52)
ss.pearsonr(params,accuracy)

(-0.5075742173410019, 0.38267167774163646)

In [12]:
gru229=(85.72, 85.47, 88.83, 86.10, 87.27)
gru232=(90.13, 88.83, 85.10, 92.05, 90.19)
ss.ttest_ind(gru229,gru232,equal_var=False)

Ttest_indResult(statistic=-1.9633680994635292, pvalue=0.09633587491316349)

In [10]:
gru232=(86.72, 87.27, 88.83, 86.72, 88.76)
gru222=(92.05, 86.78, 91.74, 90.32, 92.05)
ss.ttest_ind(gru232,gru222,equal_var=False)

Ttest_indResult(statistic=-2.636186592915551, pvalue=0.04067529976680055)

In [14]:
params=(2961,4849,6929,12753,14657,32625,50129,119505)  # one missing value
accuracy=(87.98,88.14,90.59,89.72,88.80,91.66,92.97,91.25) # one missing value
ss.pearsonr(params,accuracy)

(0.5811435861199084, 0.13083426764743972)