In [1]:
import numpy as np
X=np.ones(10)
X

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [2]:
W=np.ones(10)
W

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
dot_product = X.dot(W)
dot_product

10.0

In [13]:
W=np.ones([5,10])
print(np.shape(W),np.shape(X))

(5, 10) (10,)


In [14]:
dot_product = W.dot(X)
print(np.shape(dot_product))
dot_product

(5,)


array([10., 10., 10., 10., 10.])